export const SEMESTER_SUBJECTS = {
  BEI: {
    1: [
      "Engineering Mathematics I",
      "Computer Programming",
      "Engineering Drawing",
      "Engineering Physics",
      "Digital Logic",
      "Basic Electrical Engineering",
    ],
    2: [
      "Engineering Mathematics II",
      "Object Oriented Programming",
      "Engineering Chemistry",
      "Electric Circuit and Machine",
      "Microprocessor",
    ],
    3: [
      "Engineering Mathematics III",
      "Probability and Statistics",
      "Electronics Devices and Circuit",
      "Instrumentation",
      "Control System",
      "Electromagnetics",
    ],
    4: [
      "Professional Communication",
      "Database Management Systems",
      "Applied Mechanics",
      "Numerical Methods",
      "Electrical Circuits",
      "Digital Logic",
    ],
  },
  BCT: {
    1: [
      "Engineering Mathematics I",
      "Computer Programming",
      "Engineering Drawing",
      "Engineering Physics",
      "Digital Logic",
      "Basic Electrical Engineering",
    ],
    2: [
      "Engineering Mathematics II",
      "Data Structures",
      "Engineering Chemistry",
      "Electronics",
      "Communication Skills",
    ],
    3: [
      "Engineering Mathematics III",
      "Algorithms",
      "Digital Logic Design",
      "Microprocessors",
    ],
    4: [
      "Professional Ethics",
      "Database Management Systems",
      "Software Engineering",
      "Operating Systems",
    ],
  },
  BCE: {
    1: [
      "Mathematics I",
      "Civil Engineering Materials",
      "Engineering Drawing",
      "Physics",
      "Surveying",
    ],
    2: [
      "Mathematics II",
      "Building Technology",
      "Chemistry",
      "Mechanics",
      "Environmental Science",
    ],
    3: [
      "Mathematics III",
      "Structural Analysis",
      "Fluid Mechanics",
      "Soil Mechanics",
    ],
    4: [
      "Professional Practice",
      "Transportation Engineering",
      "Hydraulic Engineering",
      "Construction Management",
    ],
  },
};